### ISSUE TITLE
Top level 'runs:' section is required for annshiv/Hostinger-deployment/v2.1/action.yml

### ISSUE THREAD

**Issue by SKbarbon** [annshiv/Hostinger-deployment#1]
I have this issue:

```
Top level 'runs:' section is required for annshiv/Hostinger-deployment/v2.1/action.yml
```

And the action failed and nothing pushed to hostinger.

## What I did
1. I did generate SSH key, then stored it on deploy keys under deploy keys by name `Hostinger key`
2. I did create a webhook, then pasted the webhook URL on it from the one I copyed from hostinger.
3. I did create a publish.yml file, with content as following:

```yml
name: Generate a build and push to another branch

on:
  push:
    branches:
      - main # The branch name your are commit the new changes

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Deploy to Hostinger
        uses: annshiv/Hostinger-deployment@v2.1
        
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build # The build command of your project

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch name where you want to push the assets
          FOLDER: . # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
```

# Tell me whats wrong please
